# Generated by Django 4.2.20 on 2025-04-11 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
